CREATE TABLE IF NOT EXISTS TODO_LIST (
  id INT AUTO_INCREMENT  PRIMARY KEY,
  text VARCHAR(250) NOT NULL
);

CREATE TABLE IF NOT EXISTS TODO_GROUP (
  id INT AUTO_INCREMENT  PRIMARY KEY,
  group_name VARCHAR(250) NOT NULL
);

ALTER TABLE IF EXISTS TODO_LIST ADD COLUMN IF NOT EXISTS group_id INT;

ALTER TABLE IF EXISTS TODO_LIST ADD FOREIGN KEY ( group_id ) REFERENCES TODO_GROUP( id );