CREATE TABLE IF NOT EXISTS TODO_GROUP (
  id INT AUTO_INCREMENT  PRIMARY KEY,
  group_name VARCHAR(250) NOT NULL
);

CREATE TABLE IF NOT EXISTS TODO_LIST (
  id INT AUTO_INCREMENT  PRIMARY KEY,
  text VARCHAR(250) NOT NULL,
  group_id INT,
  user_id INT
);

CREATE TABLE IF NOT EXISTS USERS (
  id INT AUTO_INCREMENT PRIMARY KEY,
  login VARCHAR(250) NOT NULL,
  password VARCHAR(250) NOT NULL
);

ALTER TABLE IF EXISTS TODO_LIST ADD COLUMN IF NOT EXISTS group_id INT;
ALTER TABLE IF EXISTS TODO_LIST ADD COLUMN IF NOT EXISTS user_id INT;

ALTER TABLE IF EXISTS TODO_LIST ADD FOREIGN KEY ( group_id ) REFERENCES TODO_GROUP( id );

ALTER TABLE IF EXISTS TODO_LIST ADD FOREIGN KEY ( user_id ) REFERENCES USERS( id );

ALTER TABLE IF EXISTS USERS ADD COLUMN IF NOT EXISTS password VARCHAR(250);